-- Folios v2: revisiones identificables, roles y auditoría
-- Ejecutar en el proyecto Supabase antes de publicar el frontend de esta rama.
-- Conserva todos los registros existentes y corrige folios con más de una versión activa.

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

alter table public.informes
  add column if not exists public_id uuid default gen_random_uuid(),
  add column if not exists revision integer,
  add column if not exists operador_id uuid references auth.users(id),
  add column if not exists reemplaza_id uuid references public.informes(id),
  add column if not exists motivo_cambio text,
  add column if not exists updated_at timestamptz default now();

update public.informes
set public_id = gen_random_uuid()
where public_id is null;

with numbered as (
  select id,
         row_number() over (
           partition by upper(btrim(folio))
           order by created_at, id
         ) - 1 as revision_calculada,
         lag(id) over (
           partition by upper(btrim(folio))
           order by created_at, id
         ) as anterior_id
  from public.informes
)
update public.informes i
set revision = n.revision_calculada,
    reemplaza_id = coalesce(i.reemplaza_id, n.anterior_id)
from numbered n
where n.id = i.id
  and (i.revision is null or i.reemplaza_id is null);

-- Si el esquema anterior dejó varias filas activas, conserva como vigente la más reciente.
with activas as (
  select id,
         row_number() over (
           partition by upper(btrim(folio))
           order by created_at desc, id desc
         ) as posicion
  from public.informes
  where estado = 'activo'
)
update public.informes i
set estado = 'reemplazado',
    motivo_cambio = coalesce(i.motivo_cambio, 'Regularización automática: existían varias versiones activas'),
    updated_at = now()
from activas a
where a.id = i.id
  and a.posicion > 1;

alter table public.informes
  alter column public_id set not null,
  alter column revision set not null,
  alter column revision set default 0,
  alter column updated_at set not null;

create unique index if not exists informes_public_id_uq
  on public.informes(public_id);
create unique index if not exists informes_folio_revision_uq
  on public.informes(upper(btrim(folio)), revision);
create unique index if not exists informes_un_activo_por_folio_uq
  on public.informes(upper(btrim(folio)))
  where estado = 'activo';
create index if not exists informes_estado_fecha_idx
  on public.informes(estado, created_at desc);
create index if not exists informes_operador_idx
  on public.informes(operador_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'informes_estado_valido'
      and conrelid = 'public.informes'::regclass
  ) then
    alter table public.informes
      add constraint informes_estado_valido
      check (estado in ('activo', 'reemplazado', 'anulado')) not valid;
    alter table public.informes validate constraint informes_estado_valido;
  end if;
end $$;

create table if not exists public.operadores (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nombre text,
  rol text not null default 'operador'
    check (rol in ('operador', 'administrador')),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.operadores enable row level security;

-- El usuario ya existente queda como administrador inicial.
insert into public.operadores (user_id, email, nombre, rol, activo)
select u.id,
       u.email,
       coalesce(nullif(u.raw_user_meta_data ->> 'nombre', ''), split_part(u.email, '@', 1)),
       case
         when row_number() over (order by u.created_at, u.id) = 1
           then 'administrador'
         else 'operador'
       end,
       true
from auth.users u
on conflict (user_id) do nothing;

create table if not exists public.folio_eventos (
  id bigint generated by default as identity primary key,
  informe_id uuid references public.informes(id),
  folio text,
  accion text not null,
  detalle jsonb not null default '{}'::jsonb,
  actor_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.folio_eventos enable row level security;
create index if not exists folio_eventos_folio_fecha_idx
  on public.folio_eventos(upper(btrim(folio)), created_at desc);
create index if not exists folio_eventos_actor_idx
  on public.folio_eventos(actor_id);

create or replace function private.es_operador()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.operadores o
    where o.user_id = (select auth.uid())
      and o.activo
      and o.rol in ('operador', 'administrador')
  );
$$;

create or replace function private.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.operadores o
    where o.user_id = (select auth.uid())
      and o.activo
      and o.rol = 'administrador'
  );
$$;

revoke execute on function private.es_operador() from public, anon;
revoke execute on function private.es_admin() from public, anon;
grant execute on function private.es_operador() to authenticated;
grant execute on function private.es_admin() to authenticated;

drop policy if exists "alta autenticada" on public.informes;
drop policy if exists "lectura publica" on public.informes;
drop policy if exists informes_lectura_publica on public.informes;
drop policy if exists informes_lectura_equipo on public.informes;
drop policy if exists operadores_lectura on public.operadores;
drop policy if exists eventos_lectura_equipo on public.folio_eventos;

create policy informes_lectura_publica
on public.informes for select
to anon
using (true);

create policy informes_lectura_equipo
on public.informes for select
to authenticated
using ((select private.es_operador()));

create policy operadores_lectura
on public.operadores for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.es_admin())
);

create policy eventos_lectura_equipo
on public.folio_eventos for select
to authenticated
using ((select private.es_operador()));

revoke all on table public.informes from anon, authenticated;
revoke all on table public.operadores from anon, authenticated;
revoke all on table public.folio_eventos from anon, authenticated;

grant select (
  public_id, folio, revision, sha256, num_paginas,
  fecha_emision, estado, created_at, updated_at
) on public.informes to anon;
grant select on public.informes to authenticated;
grant select on public.operadores to authenticated;
grant select on public.folio_eventos to authenticated;

create or replace function private.registrar_revision(
  p_public_id uuid,
  p_folio text,
  p_sha256 text,
  p_num_paginas integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_folio text := upper(btrim(coalesce(p_folio, '')));
  v_sha text := lower(btrim(coalesce(p_sha256, '')));
  v_anterior public.informes%rowtype;
  v_nueva public.informes%rowtype;
  v_revision integer;
begin
  if (select auth.uid()) is null or not (select private.es_operador()) then
    raise exception 'Usuario sin permisos de operador' using errcode = '42501';
  end if;
  if v_folio = '' then
    raise exception 'El folio es obligatorio' using errcode = '22023';
  end if;
  if v_sha !~ '^[0-9a-f]{64}$' then
    raise exception 'La huella SHA-256 no es válida' using errcode = '22023';
  end if;
  if p_public_id is null then
    raise exception 'El identificador público es obligatorio' using errcode = '22023';
  end if;

  select *
  into v_anterior
  from public.informes
  where upper(btrim(folio)) = v_folio
    and estado = 'activo'
  order by created_at desc, id desc
  limit 1
  for update;

  select coalesce(max(revision), -1) + 1
  into v_revision
  from public.informes
  where upper(btrim(folio)) = v_folio;

  if v_anterior.id is not null then
    update public.informes
    set estado = 'reemplazado',
        motivo_cambio = 'Sustituido por revisión R' || lpad(v_revision::text, 2, '0'),
        updated_at = now()
    where id = v_anterior.id;

    insert into public.folio_eventos (
      informe_id, folio, accion, detalle, actor_id
    ) values (
      v_anterior.id, v_folio, 'reemplazo',
      jsonb_build_object('revision_anterior', v_anterior.revision, 'revision_nueva', v_revision),
      (select auth.uid())
    );
  end if;

  insert into public.informes (
    public_id, folio, revision, sha256, num_paginas,
    estado, operador_id, reemplaza_id, fecha_emision
  ) values (
    p_public_id, v_folio, v_revision, v_sha, p_num_paginas,
    'activo', (select auth.uid()), v_anterior.id, current_date
  )
  returning * into v_nueva;

  insert into public.folio_eventos (
    informe_id, folio, accion, detalle, actor_id
  ) values (
    v_nueva.id, v_folio, 'emision',
    jsonb_build_object('revision', v_revision, 'public_id', v_nueva.public_id),
    (select auth.uid())
  );

  return jsonb_build_object(
    'id', v_nueva.id,
    'public_id', v_nueva.public_id,
    'folio', v_nueva.folio,
    'revision', v_nueva.revision,
    'estado', v_nueva.estado,
    'replaced', case when v_anterior.id is null then 0 else 1 end
  );
end;
$$;

create or replace function public.registrar_revision(
  p_public_id uuid,
  p_folio text,
  p_sha256 text,
  p_num_paginas integer
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.registrar_revision(
    p_public_id, p_folio, p_sha256, p_num_paginas
  );
$$;

revoke execute on function public.registrar_revision(uuid, text, text, integer)
  from public, anon;
grant execute on function public.registrar_revision(uuid, text, text, integer)
  to authenticated;

create or replace function private.anular_folio(
  p_folio text,
  p_motivo text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_folio text := upper(btrim(coalesce(p_folio, '')));
  v_motivo text := btrim(coalesce(p_motivo, ''));
  v_informe public.informes%rowtype;
begin
  if (select auth.uid()) is null or not (select private.es_admin()) then
    raise exception 'Solo un administrador puede anular folios' using errcode = '42501';
  end if;
  if length(v_motivo) < 5 then
    raise exception 'Escribe un motivo de anulación' using errcode = '22023';
  end if;

  select *
  into v_informe
  from public.informes
  where upper(btrim(folio)) = v_folio
    and estado = 'activo'
  order by created_at desc, id desc
  limit 1
  for update;

  if v_informe.id is null then
    raise exception 'No existe una versión vigente para ese folio' using errcode = 'P0002';
  end if;

  update public.informes
  set estado = 'anulado',
      motivo_cambio = v_motivo,
      updated_at = now()
  where id = v_informe.id;

  insert into public.folio_eventos (
    informe_id, folio, accion, detalle, actor_id
  ) values (
    v_informe.id, v_folio, 'anulacion',
    jsonb_build_object('revision', v_informe.revision, 'motivo', v_motivo),
    (select auth.uid())
  );

  return jsonb_build_object(
    'id', v_informe.id,
    'folio', v_folio,
    'revision', v_informe.revision,
    'estado', 'anulado'
  );
end;
$$;

create or replace function public.anular_folio(
  p_folio text,
  p_motivo text
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.anular_folio(p_folio, p_motivo);
$$;

revoke execute on function public.anular_folio(text, text)
  from public, anon;
grant execute on function public.anular_folio(text, text)
  to authenticated;

create or replace function private.actualizar_operador(
  p_user_id uuid,
  p_rol text,
  p_activo boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actual public.operadores%rowtype;
  v_admins integer;
begin
  if (select auth.uid()) is null or not (select private.es_admin()) then
    raise exception 'Solo un administrador puede gestionar operadores' using errcode = '42501';
  end if;
  if p_rol not in ('operador', 'administrador') then
    raise exception 'Rol no válido' using errcode = '22023';
  end if;

  select * into v_actual
  from public.operadores
  where user_id = p_user_id
  for update;

  if v_actual.user_id is null then
    raise exception 'Operador no encontrado' using errcode = 'P0002';
  end if;

  if v_actual.rol = 'administrador'
     and v_actual.activo
     and (p_rol <> 'administrador' or not p_activo) then
    select count(*) into v_admins
    from public.operadores
    where rol = 'administrador'
      and activo
      and user_id <> p_user_id;
    if v_admins = 0 then
      raise exception 'Debe permanecer al menos un administrador activo' using errcode = '23514';
    end if;
  end if;

  update public.operadores
  set rol = p_rol,
      activo = p_activo,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.folio_eventos (
    folio, accion, detalle, actor_id
  ) values (
    null, 'operador_actualizado',
    jsonb_build_object('user_id', p_user_id, 'rol', p_rol, 'activo', p_activo),
    (select auth.uid())
  );

  return jsonb_build_object(
    'user_id', p_user_id,
    'rol', p_rol,
    'activo', p_activo
  );
end;
$$;

create or replace function public.actualizar_operador(
  p_user_id uuid,
  p_rol text,
  p_activo boolean
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.actualizar_operador(p_user_id, p_rol, p_activo);
$$;

revoke execute on function public.actualizar_operador(uuid, text, boolean)
  from public, anon;
grant execute on function public.actualizar_operador(uuid, text, boolean)
  to authenticated;

create or replace function private.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.operadores (user_id, email, nombre, rol, activo)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'nombre', ''), split_part(new.email, '@', 1)),
    'operador',
    true
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists crear_perfil_operador on auth.users;
create trigger crear_perfil_operador
after insert on auth.users
for each row execute function private.crear_perfil_usuario();

notify pgrst, 'reload schema';
